--automate creation of bookmarks
drop table if exists bookmarks;
create table bookmarks(
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    description TEXT DEFAULT 'you forgot this part',
    rating INT
);

insert into bookmarks (title, url, description, rating)
values 
    ('bookmark1', 'http://www.reddit.com', 'this is a test', 5),
    ('bookmark2', 'http://www.myspace.com', 'rawr xD', 3),
    ('bookmark3', 'http://www.nhl.com', 'lets do that hockey', 5),
    ('bookmark4', 'http://www.nickelback.com', 'pls no', 1),
    ('bookmark5', 'http://www.test.com', 'check one two', 2),
    ('BOOKMARK6', 'HTTP://WWW.ANGER.COM', 'WOKE UP FEELIN ANGERFUL', 5),
    ('bookmark7', 'http://www.rage.com', 'where you goin?', 2),
    ('bookmark8', 'http://www.spiderman.com', 'nowhere', 4),
    ('bookmark9', 'http://www.randythemachomansavage', 'paaaaiiiinnnnnnnnn', 1)